version: '3.9'

services:

  auth-service:
    build: ./services/auth-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres-auth
    env_file:
      - ./services/auth-service/.env

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  shop-service:
    build: ./services/shop-service
    ports:
      - "8002:8000"
    depends_on:
      - postgres-shop
    env_file:
      - ./services/shop-service/.env

  postgres-shop:
    image: postgres:16
    container_name: postgres-shop
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_shop_data:/var/lib/postgresql/data

  review-service:
    build: ./services/review-service
    ports:
      - "8003:8000"
    depends_on:
      - postgres-review
    env_file:
      - ./services/review-service/.env

  postgres-review:
    image: postgres:16
    container_name: postgres-review
    environment:
      POSTGRES_DB: review_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_review_data:/var/lib/postgresql/data

  gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - shop-service
      - review-service
    env_file:
      - ./services/gateway/.env
      
volumes:
  postgres_auth_data:
  postgres_shop_data:
  postgres_review_data: